trigger:
- master

pool: Default
jobs:
- job: Build
  timeoutInMinutes: 300
  variables:
    build.clean: all
    platform: x64
    version: 'ci'
    appVersion: '2.0'
    appBuild: $(Build.BuildID)
    appRevision: 0
    skipComponentGovernanceDetection: True
    
  steps:
  - task: PowerShell@2
    displayName: 'Set BuildNumber'
    inputs:
      targetType: inline
      script: 'Write-Host "##vso[build.updatebuildnumber]$(appVersion).$(appBuild).$(appRevision)"'
  - task: PowerShell@2
    displayName: 'Download symbols'
    inputs:
      targetType: inline
      script: 'bc-commands download-microsoft-symbols'  
  - task: PowerShell@2
    displayName: 'Compile artifacts'
    inputs:
      targetType: inline
      script: 'bc-commands compile-project'
      
  - task: PowerShell@2
    displayName: 'Push artifacts'
    inputs:
      targetType: inline
      script: 'bc-commands publish-library-to-npm'
      
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifacts'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: output